[project]
name = "bakalari-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "coloredlogs>=15.0.1",
    "httpx>=0.28.1",
    "mcp[cli]>=1.19.0",
]
